title: SAFE Network
description: A decentralized data storage and communications network that provides a secure, efficient and low-cost infrastructure for app developers and users.
url: "https://safenetwork.org"

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - Makefile

markdown: kramdown
kramdown:
  input: GFM
sass:
  style: :compressed

permalink: pretty
